services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 80:8000 #Host:Container
    image: app:django
    container_name: timetracker_app
    command: python manage.py runserver 0.0.0.0:8000

