# Generated by Django 4.2.1 on 2023-05-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_total_time',
            new_name='total_time',
        ),
        migrations.AddField(
            model_name='project',
            name='is_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='recording_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='recording_stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
