# Generated by Django 4.2.1 on 2023-06-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0006_alter_timeentry_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
